FROM --platform=linux/amd64 python:3.12

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./static /code/static
COPY ./templates /code/templates
COPY ./main.py /code/main.py

EXPOSE 3000

CMD ["fastapi", "run", "main.py", "--port", "3000"]