FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/python-312

WORKDIR /app

ADD requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

ADD static /app/static
ADD templates /app/templates
ADD main.py /app/main.py

ENV PORT 3000
EXPOSE 3000

CMD ["python", "main.py"]