FROM registry.access.redhat.com/ubi9/python-312

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./main.py /app/main.py

ENV PORT 8080
EXPOSE 8080

CMD ["python", "main.py"]